# Whether this GitHub repo is for a CC-led engineering project
engineering_project: true
# Name of the repository/project in English
english_name: Open Professionals Education Network (OPEN) website
# All technologies used
technologies: CSS, HTML
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
# Slack channel name (optional key)
#slack:
